# Generated by Django 5.1.1 on 2026-04-02 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.SlugField(help_text='Short unique identifier used in the room URL', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Display name for the room', max_length=200)),
                ('is_recording', models.BooleanField(default=False, help_text='True while the host is recording the meeting')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the room was created')),
                ('created_by', models.ForeignKey(help_text='The user who created this room (the host)', on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, help_text='All users who have joined this room', related_name='joined_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The text content of the message')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the message was sent')),
                ('user', models.ForeignKey(help_text='The user who sent this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(help_text='The room this message was sent in', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='videoconference_app.room')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='The uploaded file (stored in media/room_files/)', upload_to='room_files/')),
                ('original_filename', models.CharField(help_text='The original filename as uploaded by the user', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When the file was uploaded')),
                ('room', models.ForeignKey(help_text='The room this file was shared in', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='videoconference_app.room')),
                ('uploaded_by', models.ForeignKey(help_text='The user who uploaded this file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='The note content (blank is allowed)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time this note was saved')),
                ('author', models.ForeignKey(help_text='The user who wrote these notes', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(help_text='The room these notes belong to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='videoconference_app.room')),
            ],
            options={
                'unique_together': {('room', 'author')},
            },
        ),
    ]
